### ISSUE TITLE
No line break for apple security announce mail list

### ISSUE THREAD

**Issue by huangyg11** [leafac/www.kill-the-newsletter.com#10]
I subscribe to this mail list https://lists.apple.com/mailman/listinfo/security-announce/ and found the content received stip out line break which make it hard to read.

From the archive https://lists.apple.com/archives/security-announce/2019/May/msg00005.html , the content does have line break.

If you need the feed / email url, would you mind providing a private channel, so that I can send it to you privately.

Thanks.

**Comment by leafac** [comment]
Ooops, sorry about how long it took me to get to this.

Yes, I’d like to see the feed, please send it to <kill-the-newsletter@leafac.com>. I suspect that the email claims to be HTML, but it’s actually plain-text. We’ll see…

**Comment by huangyg11** [comment]
I have sent the feed url to the mailbox

**Comment by leafac** [comment]
Resolved in a private communication.
