### ISSUE TITLE
Self hosting

### ISSUE THREAD

**Issue by oliverpool** [leafac/www.kill-the-newsletter.com#18]
Hi, thank you for this great project!

I would love to self-host an instance of this service on my own server.
I have managed to make a Dockerfile to get it build and running, but I just realized that the domain name "kill-the-newsletter.com" is hard-coded everywhere.

It is not a problem for the HTML (usability suffers, but I don't care), but it is an issue for the checking of the incoming e-mails.

I would like to make a PR to allow setting the mail domain based on an environment variable (the default being `kill-the-newsletter.com`, so that you don't have to change anything to your deploy configuration).

What do you think?

**Comment by leafac** [comment]
I prepared the application for self hosting. Please [follow the instructions](https://github.com/leafac/www.kill-the-newsletter.com#deploy-your-own-instance-self-host) and let me know how it goes.

**Comment by oliverpool** [comment]
Thanks, that should be enough to self-host it!
