### ISSUE TITLE
Add TLS/STARTTLS support

### ISSUE THREAD

**Issue by Mynacol** [leafac/www.kill-the-newsletter.com#71]
Hi, first of all: Thanks for this incredible service. I really love it! :heart: 

Unfortunately, I noticed that the main instance, *kill-the-newsletter.com* (thanks for hosting) does not support STARTTLS, which is a no-go IMO. The used smtp-server library [has support for it](https://nodemailer.com/extras/smtp-server/#tls-and-startls-notice), but you [disable it](https://github.com/leafac/kill-the-newsletter/blob/main/source/index.ts#L434).

Enabling support seems to be relatively easy:
First, [do not disable](https://github.com/leafac/kill-the-newsletter/blob/main/source/index.ts#L434) the STARTTLS command.
Second, set up `key`, `cert` and eventually `ca` parameters to point to the certificate you already have for HTTPS.

Congrats, you have enabled encryption! :confetti_ball: 

---

Additionally, if you are already at it, check recommendations from [internet.nl](https://internet.nl/mail/kill-the-newsletter.com/):
- Add a [DANE record](https://www.huque.com/bin/gen_tlsa) pinning the [Let's Encrypt CA certificates](https://letsencrypt.org/certificates/). Pinning the two CA certificates makes the TLSA records safe for the next decades. You just have to stick to Let's Encrypt. They should be:
  ```
  # ISRG Root X1
  _25._tcp.kill-the-newsletter.com.	10800	IN	TLSA	2 1 1 0b9fa5a59eed715c26c1020c711b4f6ec42d58b0015e14337a39dad301c5afc3
  # ISRG Root X2
  _25._tcp.kill-the-newsletter.com.	10800	IN	TLSA	2 1 1 762195c225586ee6c0237456e2107dc54f1efc21f61a792ebd515913cce68332
  ```
  You already have the required DNSSEC on the kill-the-newsletter.com domain.
  You can use [this test page](https://dane.sys4.de/) if you have deployed it.
- Add IPv6 support to the mail server. It's 2022, IPv6 should be supported by default. And as you only receive mails, you should not fear deliverability problems.
- Avoid misuse of your domain for spam. Also see [this Cloudflare article](https://www.cloudflare.com/learning/dns/dns-records/protect-domains-without-email/).
  - Add a SPF record. If you never send email from your domain, just set
    ```
    kill-the-newsletter.com.	10800	IN	TXT	"v=spf1 -all"
    ```
    Alternatively `v=spf1 mx -all` to allow the mail server to send mail.
  - Eventually add a null DKIM record as described by the Cloudflare article. Cloudflare wants to set the wildcard record `*._domainkey.kill-the-newsletter.com`, check if your DNS provider supports wildcard records.
  - Add a DMARC record rejecting mail for failing SPF/DKIM checks
  ```
  _dmarc.kill-the-newsletter.com.	10800	IN	TXT	"v=DMARC1; p=reject;"
  ```

You can also consult [hardenize.com](https://www.hardenize.com/) for great email server reports.

**Comment by leafac** [comment]
> Hi, first of all: Thanks for this incredible service. I really love it! ❤️

Thanks for the kind words.

---

When I was developing Kill the Newsletter! I thought about doing what you’re proposing and use the HTTPS keys for the email server. But then I thought: How will the email server pick up new TLS keys when they’re renewed (automatically) by the HTTPS server? I suppose it would have to hook into some event system from the HTTPS server, or monitor the filesystem, or something to that effect. And at that point I disabled STARTTLS 🤷

Do you have a better answer for this?

---

Thanks for the other recommendations. I’ll look into them…

**Comment by leafac** [comment]
Hi @Mynacol,

Yes, the solution really ended up being monitoring the filesystem for updates on the certificate and restarting the email server.

I’ll look into the other suggestions in the near future. Thank you very much.
