### ISSUE TITLE
Expiration Date

### ISSUE THREAD

**Issue by AaronKnowls** [leafac/www.kill-the-newsletter.com#91]
Sorry I couldn't find any related information.

Is there an expiration date for created feeds?

Thank you so so much for this service. Incredibly useful, been using it for years. Thank you, Leandro!!

**Comment by leafac** [comment]
Hi @AaronKnowls,

Thanks for the kind words!

I added a section [to the website](https://kill-the-newsletter.com/) explaining this: “Why are old entries disappearing?”

Best.
